//user list constants
export const GET_USER_LIST = 'GET USER_LIST';
export const GET_USER_LIST_FULFILLED = 'GET_USER_LIST_FULFILLED';
export const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR';

//user details constans
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_FULFILLED = 'GET_USER_DETAILS_FULFILLED';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';
